### ISSUE TITLE
Project Checklist

### ISSUE THREAD

**Issue by dbarjs** [elbitdigital/base#1]
## Meta:

[Descrição de uma linha] 
## Tarefas:
- [x] Diretório do projeto no Github
- [x] Importação do diretório BASE
- [ ] Arquivo de logo (SVG)
- [ ] Lib. de ícones (Fontello)
- [ ] Projeto no Typekit
- [ ] Projeto no Firebase
- [x] Configurações de deploy do Firebase
- [ ] Configuração do domínio (DNS)
- [ ] Configuração de emails
- [ ] Projeto no Analytics
- [ ] Confirmar propriedade no Google Search Console
- [ ] Definição do nome de projeto (GulpFile)
- [ ] Definição do nome de projeto (_.js)
- [ ] Definição do nome de projeto (_.css)
- [ ] Configuração do arquivo package.json
- [ ] Construção dos arquivos de distribuição
- [x] Definição de dependências de desenvolvimento (npm)
